import { ArrowLeft, ArrowUpRight } from 'lucide-react'
import './HaesiivoojaCase.css'
const play = 'https://play.google.com/store/apps/details?id=com.cleanerfinder'
const screens = [
 {file:'haesiivooja-login.png',title:'A familiar starting point',text:'Email and social sign-in give customers several ways in. The next question is whether account creation can wait until a customer understands the service.',alt:'Published HaeSiivooja sign-in screen'},
 {file:'haesiivooja-services.png',title:'Make the scope tangible',text:'Named cleaning types and optional extras turn “I need a cleaner” into a specific request. Clear inclusions matter more than adding more choices.',alt:'Published HaeSiivooja service selection and optional extras'},
 {file:'haesiivooja-cleaner.png',title:'Design for the other side',text:'Bookings, availability and services sit in the cleaner’s workspace. A customer journey only works when the provider can respond and manage the work.',alt:'Published HaeSiivooja cleaner dashboard'},
]
export default function HaesiivoojaCase({back}:{back:()=>void}) {
 return <main className="hc" id="top">
  <button className="back" onClick={back}><ArrowLeft size={18}/> All projects</button>
  <div className="hc-intro"><p className="overline">HAESIIVOOJA / SERVICE MARKETPLACE</p><h1>From “I need a cleaner”<br/><em>to a clear next step.</em></h1><p>Designing a connected experience for people booking a clean and the professionals delivering it.</p><a href="https://haesiivooja.fi" target="_blank" rel="noreferrer">Visit the live product <ArrowUpRight size={16}/></a></div>
  <figure className="hc-hero"><div className="hc-hero-copy"><span>ONE SERVICE.<br/>TWO CONNECTED JOURNEYS.</span><p>Choose the service.<br/>Coordinate the work.<br/>Know what happens next.</p><small>Published Android interface</small></div><div className="hc-phones">{screens.map(s=><img key={s.file} src={`/cases/${s.file}`} alt={s.alt}/>)}</div><figcaption>Customer access → service selection → cleaner work management. Original screens from the Google Play listing.</figcaption></figure>
  <dl className="hc-facts"><div><dt>MY ROLE</dt><dd>Product & UX/UI designer</dd></div><div><dt>DESIGN SCOPE</dt><dd>Journeys, flows, interactions & UI</dd></div><div><dt>PLATFORMS</dt><dd>Web & Android</dd></div><div><dt>STATUS</dt><dd>Live product + portfolio demo</dd></div></dl>
  <nav className="hc-nav" aria-label="Case study sections">{[['context','The challenge'],['decisions','Design thinking'],['screens','The interface'],['prototype','Try the journey'],['reflection','What comes next']].map(([id,label])=><button key={id} onClick={()=>document.getElementById(`hc-${id}`)?.scrollIntoView({behavior:'smooth'})}>{label}</button>)}</nav>
  <section className="hc-section hc-split" id="hc-context"><p className="overline">01 / FRAME THE PROBLEM</p><div><h2>A booking is a decision<br/>about scope and trust.</h2><p>Customers need more than a list of cleaners. They need to understand what a service includes, whether it fits their home and how a request becomes a confirmed appointment.</p><p>Cleaners need an equally clear picture of the work: the service, timing and booking status. I treat these as two sides of one product rather than separate interfaces.</p><div className="hc-note"><strong>My ownership</strong><p>I owned the product and UX/UI design work: framing the experience, shaping the customer and cleaner journeys, and translating them into flows, interactions and interface design.</p></div></div></section>
  <section className="hc-section" id="hc-decisions"><p className="overline">02 / PRODUCT THINKING</p><h2>Reduce uncertainty at each decision.</h2><p className="hc-lead">These design hypotheses guide the experience. They are questions to validate, not reported research findings.</p><div className="hc-cards"><article><small>01 / SCOPE</small><h3>What am I booking?</h3><p>Separate the cleaning type from optional extras. Show a readable summary before the customer commits.</p><b>Test: can people explain what is included?</b></article><article><small>02 / COORDINATION</small><h3>Does this work for both sides?</h3><p>Connect customer requests to the cleaner’s availability and work queue. Keep requested and confirmed states distinct.</p><b>Test: is the next action clear to both roles?</b></article><article><small>03 / CONFIDENCE</small><h3>What happens next?</h3><p>Make status and next steps visible after submission. A request should not look like a confirmed booking.</p><b>Test: can people identify whether it is confirmed?</b></article></div>
  <div className="hc-journey"><div><small>CUSTOMER</small><ol><li>Define the clean</li><li>Choose provider & time</li><li>Review the request</li><li>Track confirmation</li></ol></div><div><small>CLEANER</small><ol><li>Set services & availability</li><li>Review incoming request</li><li>Accept the work</li><li>Manage the appointment</li></ol></div><p>A shared booking status connects the two journeys.</p></div></section>
  <section className="hc-section" id="hc-screens"><p className="overline">03 / THE PUBLISHED INTERFACE</p><h2>One product, different responsibilities.</h2><p className="hc-lead">Selected original Android screens. Open any image to inspect the details.</p><div className="hc-screen-grid">{screens.map(s=><figure key={s.file}><a href={`/cases/${s.file}`} target="_blank" rel="noreferrer"><img src={`/cases/${s.file}`} alt={s.alt} loading="lazy"/></a><figcaption><h3>{s.title}</h3><p>{s.text}</p></figcaption></figure>)}</div><p className="hc-caption">Source: <a href={play} target="_blank" rel="noreferrer">HaeSiivooja on Google Play ↗</a>. Screens contain sample account information; the displayed values are not portfolio performance metrics.</p></section>
  <section className="hc-section hc-prototype" id="hc-prototype"><div><p className="overline">04 / INTERACTIVE WALKTHROUGH</p><h2>Try the connected<br/>booking journey.</h2><p>Choose a cleaning type, add an extra, select a sample cleaner and review a request. Then switch to the cleaner’s view to confirm it.</p><div className="hc-note"><strong>Portfolio prototype</strong><p>This illustrative walkthrough was created for this case study. It explores the design hypotheses above; it is not the original production app or a live booking service. Names, prices and availability are sample data.</p></div><a href="/haesiivooja-prototype.html" target="_blank" rel="noreferrer">Open prototype in a new tab <ArrowUpRight size={16}/></a></div><iframe src="/haesiivooja-prototype.html" title="Interactive HaeSiivooja customer and cleaner booking prototype" loading="lazy" sandbox="allow-scripts"/></section>
  <section className="hc-section hc-split" id="hc-reflection"><p className="overline">05 / VALIDATION & REFLECTION</p><div><h2>A live product is a starting point,<br/>not proof of impact.</h2><p>HaeSiivooja is published on the web and Android. This case does not claim measured conversion improvements or completed user-testing results.</p><h3>What I would validate next</h3><ul><li><strong>Comprehension:</strong> ask customers to explain the service, extras and booking status in their own words.</li><li><strong>Task completion:</strong> observe a first booking, recording hesitation, errors and completion without help.</li><li><strong>Provider coordination:</strong> test whether cleaners understand the scope and can accept or decline a request confidently.</li></ul><p>My central design lesson: confidence comes from clear scope and visible coordination. A polished booking screen has limited value if either person is unsure what happens next.</p><div className="links"><a href="https://haesiivooja.fi" target="_blank" rel="noreferrer">Explore HaeSiivooja <ArrowUpRight size={16}/></a><a href={play} target="_blank" rel="noreferrer">View Android app <ArrowUpRight size={16}/></a></div></div></section>
  <a className="next" href="#case-aura"><small>UP NEXT</small>Aura <ArrowUpRight/></a>
 </main>
}
